// <auto-generated />
using System;
using DB_Conection_Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DB_Conection_Models.Migrations
{
    [DbContext(typeof(PCDbContext))]
    [Migration("20230810151544_NewDB")]
    partial class NewDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DB_Conection_Models.Models.Motherboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Motherboards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AsRock B450"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gigabyte B550"
                        },
                        new
                        {
                            Id = 3,
                            Name = "MSI X570"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ASUS ROG Strix Z590"
                        },
                        new
                        {
                            Id = 5,
                            Name = "ASRock X470"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Gigabyte B460"
                        },
                        new
                        {
                            Id = 7,
                            Name = "MSI B360"
                        },
                        new
                        {
                            Id = 8,
                            Name = "ASUS Prime A520"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Gigabyte H470"
                        },
                        new
                        {
                            Id = 10,
                            Name = "MSI B450"
                        });
                });

            modelBuilder.Entity("DB_Conection_Models.Models.PC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPCComponent")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PCs");
                });

            modelBuilder.Entity("DB_Conection_Models.Models.PCCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PCCases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "NZXT H510"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fractal Design Meshify C"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cooler Master MasterBox MB311L"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Corsair 4000D"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Phanteks Eclipse P400A"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Lian Li PC-O11 Dynamic"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Thermaltake Versa H18"
                        },
                        new
                        {
                            Id = 8,
                            Name = "InWin 303"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Be Quiet! Pure Base 500DX"
                        },
                        new
                        {
                            Id = 10,
                            Name = "NZXT H710i"
                        });
                });

            modelBuilder.Entity("DB_Conection_Models.Models.PCComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdMotherboard")
                        .HasColumnType("int");

                    b.Property<int?>("IdPCCase")
                        .HasColumnType("int");

                    b.Property<int?>("IdPowerSupply")
                        .HasColumnType("int");

                    b.Property<int?>("IdProcessor")
                        .HasColumnType("int");

                    b.Property<int?>("IdRAM")
                        .HasColumnType("int");

                    b.Property<int?>("IdSSDM2")
                        .HasColumnType("int");

                    b.Property<int?>("IdVideoCard")
                        .HasColumnType("int");

                    b.Property<int>("MotherboardId")
                        .HasColumnType("int");

                    b.Property<int>("PCCaseId")
                        .HasColumnType("int");

                    b.Property<int>("PowerSupplyId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessorId")
                        .HasColumnType("int");

                    b.Property<int>("RAMId")
                        .HasColumnType("int");

                    b.Property<int>("SSDM2Id")
                        .HasColumnType("int");

                    b.Property<int>("VideoCardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MotherboardId");

                    b.HasIndex("PCCaseId");

                    b.HasIndex("PowerSupplyId");

                    b.HasIndex("ProcessorId");

                    b.HasIndex("RAMId");

                    b.HasIndex("SSDM2Id");

                    b.HasIndex("VideoCardId");

                    b.ToTable("PCComponents");
                });

            modelBuilder.Entity("DB_Conection_Models.Models.PowerSupply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PowerSupplys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Corsair RM750x"
                        },
                        new
                        {
                            Id = 2,
                            Name = "EVGA Supernova 850 GA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Seasonic Focus GX-650"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Thermaltake Toughpower GF1 750W"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Be Quiet! Straight Power 11 750W"
                        },
                        new
                        {
                            Id = 6,
                            Name = "NZXT C850"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cooler Master MWE Gold 750 V2"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Fractal Design Ion+ 760P"
                        },
                        new
                        {
                            Id = 9,
                            Name = "SilverStone SX800-LTI"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Seasonic Prime TX-1000"
                        });
                });

            modelBuilder.Entity("DB_Conection_Models.Models.Processor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Processors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AMD Ryzen 5 5600X"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Intel Core i7-11700K"
                        },
                        new
                        {
                            Id = 3,
                            Name = "AMD Ryzen 7 5800X"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Intel Core i9-12900K"
                        },
                        new
                        {
                            Id = 5,
                            Name = "AMD Ryzen 9 5900X"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Intel Core i5-11600K"
                        },
                        new
                        {
                            Id = 7,
                            Name = "AMD Ryzen 5 5800"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Intel Core i5-11400"
                        },
                        new
                        {
                            Id = 9,
                            Name = "AMD Ryzen 7 5700G"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Intel Core i7-12700K"
                        });
                });

            modelBuilder.Entity("DB_Conection_Models.Models.RAM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RAMs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Corsair Vengeance LPX 16GB"
                        },
                        new
                        {
                            Id = 2,
                            Name = "G.Skill Ripjaws V 32GB"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Crucial Ballistix 8GB"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kingston HyperX Fury 16GB"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Team T-FORCE Vulcan Z 32GB"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Corsair Dominator Platinum RGB 64GB"
                        },
                        new
                        {
                            Id = 7,
                            Name = "ADATA XPG Spectrix D60G 16GB"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Patriot Viper Steel 8GB"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Crucial Ballistix RGB 32GB"
                        },
                        new
                        {
                            Id = 10,
                            Name = "HyperX Fury RGB 16GB"
                        });
                });

            modelBuilder.Entity("DB_Conection_Models.Models.SSDM2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SSDM2s");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Samsung 970 EVO Plus 500GB"
                        },
                        new
                        {
                            Id = 2,
                            Name = "WD Blue SN550 1TB"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Crucial P1 500GB"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sabrent Rocket Q 2TB"
                        },
                        new
                        {
                            Id = 5,
                            Name = "ADATA XPG SX8200 Pro 1TB"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kingston A2000 250GB"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Seagate FireCuda 510 1TB"
                        },
                        new
                        {
                            Id = 8,
                            Name = "HP EX950 2TB"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Corsair MP600 2TB"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gigabyte AORUS NVMe Gen4 1TB"
                        });
                });

            modelBuilder.Entity("DB_Conection_Models.Models.VideoCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "NVIDIA GeForce RTX 3080"
                        },
                        new
                        {
                            Id = 2,
                            Name = "AMD Radeon RX 6800 XT"
                        },
                        new
                        {
                            Id = 3,
                            Name = "NVIDIA GeForce RTX 3070"
                        },
                        new
                        {
                            Id = 4,
                            Name = "AMD Radeon RX 6700 XT"
                        },
                        new
                        {
                            Id = 5,
                            Name = "NVIDIA GeForce RTX 3060 Ti"
                        },
                        new
                        {
                            Id = 6,
                            Name = "AMD Radeon RX 6600 XT"
                        },
                        new
                        {
                            Id = 7,
                            Name = "NVIDIA GeForce GTX 1660 Super"
                        },
                        new
                        {
                            Id = 8,
                            Name = "AMD Radeon RX 5500 XT"
                        },
                        new
                        {
                            Id = 9,
                            Name = "NVIDIA GeForce RTX 3090"
                        },
                        new
                        {
                            Id = 10,
                            Name = "AMD Radeon RX 6900 XT"
                        });
                });

            modelBuilder.Entity("DB_Conection_Models.Models.PCComponent", b =>
                {
                    b.HasOne("DB_Conection_Models.Models.Motherboard", "Motherboard")
                        .WithMany()
                        .HasForeignKey("MotherboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB_Conection_Models.Models.PCCase", "PCCase")
                        .WithMany()
                        .HasForeignKey("PCCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB_Conection_Models.Models.PowerSupply", "PowerSupply")
                        .WithMany()
                        .HasForeignKey("PowerSupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB_Conection_Models.Models.Processor", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB_Conection_Models.Models.RAM", "RAM")
                        .WithMany()
                        .HasForeignKey("RAMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB_Conection_Models.Models.SSDM2", "SSDM2")
                        .WithMany()
                        .HasForeignKey("SSDM2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB_Conection_Models.Models.VideoCard", "VideoCard")
                        .WithMany()
                        .HasForeignKey("VideoCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motherboard");

                    b.Navigation("PCCase");

                    b.Navigation("PowerSupply");

                    b.Navigation("Processor");

                    b.Navigation("RAM");

                    b.Navigation("SSDM2");

                    b.Navigation("VideoCard");
                });
#pragma warning restore 612, 618
        }
    }
}
